import 'package:hive/hive.dart';

part 'breathing_preferences.g.dart'; // We will use hive_generator or write manually. Let's write manually in this same directory to skip build_runner if needed, but it's generated by build_runner. Wait, I will use build_runner.

@HiveType(typeId: 0)
class BreathingPreferences extends HiveObject {
  @HiveField(0)
  int simpleDurationSeconds; // e.g., 3, 4, 5, 6

  @HiveField(1)
  int rounds; // e.g., 2, 4, 6, 8

  @HiveField(2)
  bool soundEnabled;

  @HiveField(3)
  bool advancedTimingEnabled;

  @HiveField(4)
  int breatheInSeconds;

  @HiveField(5)
  int holdInSeconds;

  @HiveField(6)
  int breatheOutSeconds;

  @HiveField(7)
  int holdOutSeconds;

  BreathingPreferences({
    this.simpleDurationSeconds = 4,
    this.rounds = 4,
    this.soundEnabled = true,
    this.advancedTimingEnabled = false,
    this.breatheInSeconds = 4,
    this.holdInSeconds = 4,
    this.breatheOutSeconds = 4,
    this.holdOutSeconds = 4,
  });

  BreathingPreferences copyWith({
    int? simpleDurationSeconds,
    int? rounds,
    bool? soundEnabled,
    bool? advancedTimingEnabled,
    int? breatheInSeconds,
    int? holdInSeconds,
    int? breatheOutSeconds,
    int? holdOutSeconds,
  }) {
    return BreathingPreferences(
      simpleDurationSeconds:
          simpleDurationSeconds ?? this.simpleDurationSeconds,
      rounds: rounds ?? this.rounds,
      soundEnabled: soundEnabled ?? this.soundEnabled,
      advancedTimingEnabled:
          advancedTimingEnabled ?? this.advancedTimingEnabled,
      breatheInSeconds: breatheInSeconds ?? this.breatheInSeconds,
      holdInSeconds: holdInSeconds ?? this.holdInSeconds,
      breatheOutSeconds: breatheOutSeconds ?? this.breatheOutSeconds,
      holdOutSeconds: holdOutSeconds ?? this.holdOutSeconds,
    );
  }
}
